### ISSUE TITLE
Quantum Resistant Ledger

### ISSUE THREAD

**Issue by surg0r** [Droplexprotocol/DROPLEX#1]
Hi,

Founder and lead dev of the QRL here. 

You appear to have completely copied and pasted our unlicensed QRL test code into your repo by accident!

I suggest you remove it from this repo immediately..

**Comment by crutor0x** [comment]
Isn't it open source?

**Comment by surg0r** [comment]
No. You have taken unlicensed code from an old alpha branch of our last testnet build.

Be a darling and delete it or I'll contact GitHub and have it done for you..

Kindest regards,
